### ISSUE TITLE
js9_build -lp

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/developer#37] opened 2017-06-10 05:37 UTC
![image](https://user-images.githubusercontent.com/6021844/27000341-977f2920-4daf-11e7-8621-bb779b570541.png)

doesn't install the libs & portal

**Comment by despiegk** [comment] 2017-06-10 05:38
make sure fix also on 9.00 branch

**Comment by maxux** [comment] 2017-06-10 12:38
When an error occure, log message is printed.

This error was caused by a missing dependency during the setup, fixed on master now

**Closed** 2017-06-10 13:27 UTC
Labels: priority_critical
